export const topics = {
  javascript: [
    "Random",
    "Variables",
    "Data types",
    "Functions",
    "Conditional Statements",
    "Loops",
    "Arrays",
    "Objects",
    "DOM manipulation",
    "Events",
    "Basic syntax",
    "Closures",
    "Scope",
    "Higher-order Functions",
    "Promises",
    "Async/Await",
    "ES6+ features",
    "Regular Expressions",
    "Error Handling",
    "Debugging",
    "Design Patterns",
    "Modules (CommonJS, ES6)",
    "AJAX and Fetch API",
    "WebSockets",
    "Web Storage",
    "Cookies",
    "Local and Session Storage",
    "Web Workers",
    "Service Workers",
    "WebAssembly",
    "Security Best Practices",
    "Functional Programming Concepts",
    "Design Principles",
    "Prototype and Inheritance",
  ],
  react: [
    "Random",
    "JSX",
    "Components",
    "Props",
    "State",
    "Lifecycle Methods",
    "Event Handling",
    "Conditional Rendering",
    "Lists and Keys",
    "Forms",
    "Hooks",
    "Class Components",
    "React Router",
    "React Context",
    "Redux",
    "React Hooks in-depth",
    "React Router Advanced Features",
    "Higher-Order Components (HOC)",
    "React Performance Optimization",
    "Code Splitting",
    "Next.js Basics",
    "Testing in React",
  ],
  css: [
    "Random",
    "Selectors",
    "Box Model",
    "Layouts",
    "Typography",
    "Colors and Backgrounds",
    "CSS Units",
    "Grid",
    "Flexbox",
    "Display and Visibility",
    "CSS Pseudo-classes",
    "CSS Pseudo-elements",
    "Transitions and Animations",
    "Responsive Web Design",
    "CSS Variables",
    "CSS Frameworks (e.g., Bootstrap)",
    "Sass and Less Preprocessors",
    "CSS Methodologies (BEM, SMACSS, etc.)",
    "CSS-in-JS Libraries",
    "Critical Rendering Path",
    "CSS Grid Frameworks (e.g., Tailwind CSS)",
    "CSS Tooling (PostCSS, Autoprefixer)",
  ],
  vuejs: [
    "Random",
    "Vue Instance",
    "Components",
    "Props and Custom Events",
    "Vue Directives",
    "Computed Properties and Watchers",
    "Conditional Rendering in Vue",
    "List Rendering",
    "Forms and v-model",
    "Vue Lifecycle Hooks",
    "Vue Router",
    "VueX (State Management)",
    "Mixins",
    "Filters",
    "Custom Directives",
    "Vue.js and REST API",
    "Vue.js and AJAX",
    "Vue.js and WebSockets",
  ],
}
